### ISSUE TITLE
Java lang NoSuchMethodError BukkitServer#getOnlinePlayers

### ISSUE THREAD

**Issue by ziloka** [EricLangezaal/ZombieApocalypse#1]
Expected result:
Spawn zombies at 8pm

Actual Result:
![Capture](https://user-images.githubusercontent.com/50429450/102561975-110fe280-40a4-11eb-957e-7f82cb067f19.PNG)

**Comment by EricLangezaal** [comment]
This is not my plugin:). Apparently you have another plugin called ZombieApocalypse on your server. I can see this as the package in question is `com.gmail.deathbysniper727.zombieapocalypse`, which is not me. See how my code on this repo is under `com.ericdebouwer.zombieapocalypse`? My plugin also doesn't have the class ZAStarter, nor does it have `ZombieApocalypse#getPlayersInvolved()`. I spend some time looking for you, and you seem to have [this](https://dev.bukkit.org/projects/zombieapocalypse/files/778026) massively outdated Bukkit plugin from 2014. How you ended up with my GitHub I do not know.

**Comment by ziloka** [comment]
Anyway I believe this is where I got the plugin https://www.spigotmc.org/resources/zombieapocalypse-8-zombie-types.82106/
And it said that the source code was in this repo so here I am

**Comment by EricLangezaal** [comment]
Yeah that is my plugin. But you have installed the wrong one somewhere (or have both on your server). As I said in my previous post the plugin causing the error is the one I linked from 2014. Just delete all ZombieApocalypse plugins first and then install the one from my Spigot page you linked.
