### ISSUE TITLE
1.20.4 Heads/Skulls API flooded console.

### ISSUE THREAD

**Issue by BaxAndrei** [EricLangezaal/ZombieApocalypse#18]
```
[09:31:46] [Server thread/WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
```

**Comment by EricLangezaal** [comment]
Thank you for reporting this. Apparently Spigot has decided to enforce their new (1.18+ only) API, therefore leading to warnings (even though there is no real consequence yet) for any plugin that features customs skulls and cares about backwards compatibility somewhat, unlike Spigot. Luckily I found a reflection approach that should work on both older and new Minecraft versions without warnings, please see the new update. I didn't test really thoroughly, so do let me know if I missed something by (re)-opening the issue.

**Comment by BaxAndrei** [comment]
Everything seems to be going well now, no more errors/warnings appear in the console. Thank you.
