### ISSUE TITLE
The minutes the apocalypse should last for must be an integer

### ISSUE THREAD

**Issue by MartinFrog** [EricLangezaal/ZombieApocalypse#2]
![image](https://user-images.githubusercontent.com/60502184/113153259-7cec1480-9269-11eb-810c-6d98b219a8d4.png)

So I keep getting this message every time i try to start the apocalypse. It happens no matter what number or dimension i choose, and appears if I leave the field empty too. 
I would appreciate advice or fixes, thanks

**Comment by EricLangezaal** [comment]
Instead of giving me a chance to help you, you have decided to post a very negative review... This to me feels really unfair, as I have zero chance to help you beforehand and it could very well be a user error (not saying it is, it could be based on what you describe). If you want me to help, please delete your review first. Its very likely I can help you easily, but won’t do it like this.

**Comment by MartinFrog** [comment]
Sorry for the review, I didn’t mean any hate in it but the tone probably said otherwise, but now i deleted it.

**Comment by EricLangezaal** [comment]
Okay. What is the exact command you are using?
Keep in mind that the correct syntax is `/apo start worldname duration`, so when specifying the duration you **have to** specify the name of the world too. An example would be `/apo start myworld 10`. That is why I specify the commands like that on my plugins page, which I just updated to say this more explicitely.

It is also possible to start the apocalypse indefinitely (so until manually ended) in which case you would do `/apo start myworld`, or even `/apo start` if you are already standing in `myworld`.

**Comment by MartinFrog** [comment]
I just rechecked my syntax in-game, and it still has the same problem. However, if I don't specify the world and duration by doing /apo start, I get an internal error. 
![image](https://user-images.githubusercontent.com/60502184/113292060-88514580-9326-11eb-80a8-80ffa561e06a.png)

**Comment by EricLangezaal** [comment]
Ah that is definitely not what should happen:). I have an idea what could be the problem, but just to double check: can you give me the error it gives in **console**? That is where it explains what really happened. If you are unsure which parts, just send it whole, I know where to look.

**Comment by EricLangezaal** [comment]
@MartinFrog Is it resolved for you? If not, please send me the console error. Otherwise I think I will close this issue.

**Comment by EricLangezaal** [comment]
I am going to assume this is fixed due to no longer getting a response. Update 1.3.1 also fixed a bug which could cause starting the apocalypse to crash if the name of the world contained weird characters.
