### ISSUE TITLE
Add to config the ability for zombies to either despawn or not despawn when the apocalypse ends

### ISSUE THREAD

**Issue by pvsmagbojos** [EricLangezaal/ZombieApocalypse#3]
Currently, zombies immediately despawn whenever an apocalypse event ends. This becomes very awkward when a nightly zombie raid that lasts till morning suddenly despawns the moment the nightly raid is considered finished (a command to end the apocalypse is done)

**Comment by archonxgames** [comment]
Also, if you're interested in seeing a possible application for your plugin, I can send you my server's details in pm, thanks! And great work on this plugin btw.

**Comment by EricLangezaal** [comment]
> Currently, zombies immediately despawn whenever an apocalypse event ends. This becomes very awkward when a nightly zombie raid that lasts till morning suddenly despawns the moment the nightly raid is considered finished (a command to end the apocalypse is done)

That is a good suggestion indeed! I made it remove them so as to make sure normal monsters start spawning as soon as the apocalypse ends (to prevent the custom zombies from filling the mobcap), but having a setting for something like this is indeed logical. Will add it next update! You are just a little late haha, as I just updated this plugin so it will take a while before I will update it again. I want to make sure I bundle features in an update (and want to see if other suggestions come up now), mostly to make updating worth it for everyone. So could be a while before I update again, but will be added next update.

**Comment by EricLangezaal** [comment]
> Also, if you're interested in seeing a possible application for your plugin, I can send you my server's details in pm, thanks! And great work on this plugin btw.

Sure, always interesting to see how my plugins are used! Are you both part of the same server network btw? Otherwise this is quite an interesting place to contact me haha.

**Comment by archonxgames** [comment]
Yeah, I just accidentally used my work account while writing the suggestion and realized it only after I posted the issue haha

**Comment by EricLangezaal** [comment]
Added in the latest update: https://www.spigotmc.org/resources/zombieapocalypse-8-zombie-types.82106/update?update=406087
