### ISSUE TITLE
Add to config the ability for zombies to spawn under the effects of daylight

### ISSUE THREAD

**Issue by archonxgames** [EricLangezaal/ZombieApocalypse#4]
This might be a difficult one, but making zombies able to spawn in broad daylight can make the apocalypse more intriguing and allows for a wider variety of scenarios to play out.

**Comment by EricLangezaal** [comment]
I definitely understand the idea. It is not really feasible however. My plugin currently just replaces vanilla monster spawns by custom zombies, as that is the only performant/manageable way to do custom spawns that feel natural and abide to other default vanilla mechanics (light level for one, so as to prevent them from spawning inside houses). Recreating a spawning system would be a performance-eater, error prone and an enormous effort (to the level where it becomes unmanageable). There currently is no way to change this while keeping cross-version compatibility.

Replacing other (non monster) entities might seem like a solution. This too won't work however, as animals for example don't really spawn, they generate. What I mean by this is that they are created when a chunk generates for the first time, they don't spawn in loaded chunks (they walk around a little bit, but will stay near where they generated). This is very much unlike monsters, which do spawn near players in already loaded chunks. So this isn't possible either, as it wouldn't make them spawn in existing chunks. 

So for now it has to be night for zombies to spawn in the open unfortunately, perhaps lock the day night cycle to night always (I understand if this is not possible of course)

**Comment by archonxgames** [comment]
Would it be possible to introduce spawner mechanics in this sense? Creating invisible spawners around a certain radius of a player perhaps can solve this issue?

**Comment by EricLangezaal** [comment]
That would be completely recreating vanilla spawning. Whilst technically possible, it is incredibly difficult and will not perform well, I also covered it in the first paragraph of my message above (along with the caveats). This is also not really in the scope of my plugin, as it just changes vanilla spawning entirely, which I don't (want to) do. You could get another plugin (don't know if they exist) that does this however and my plugin will also replace their spawns. So if you have a plugin that makes extra monsters spawn, my plugin should be able to overwrite those too.

**Comment by joex92** [comment]
Hey @EricLangezaal what about adding a feature to the `/zombie` command?
instead of only giving eggs, also give spawners, something like this:
`/zombie spawner boomer` or `/zombie egg boomer`
I have _SilkSpawners_ and tried to use an egg from your plugin on a spawner, but it didn't work, it just spawns normal zombies, only if the apocalypse is active they will change to the plugin's zombies but randomly... 

I believe giving a spawner won't be so "non-vanilla" like...

**Comment by EricLangezaal** [comment]
> Hey @EricLangezaal what about adding a feature to the `/zombie` command?
> instead of only giving eggs, also give spawners, something like this:
> `/zombie spawner boomer` or `/zombie egg boomer`
> I have _SilkSpawners_ and tried to use an egg from your plugin on a spawner, but it didn't work, it just spawns normal zombies, only if the apocalypse is active they will change to the plugin's zombies but randomly...
> 
> I believe giving a spawner won't be so "non-vanilla" like...

That is an interesting idea actually, will see if it is doable! Yeah it is fundamentally not possible to create truly new entities in a plugin, so for another plugin like SilkSpawner they will just look like normal zombie eggs.

Btw this is quite an interesting place to contact me, as the original issue is closed, but sure haha.

**Comment by joex92** [comment]
> > Hey @EricLangezaal what about adding a feature to the `/zombie` command?
> > instead of only giving eggs, also give spawners, something like this:
> > `/zombie spawner boomer` or `/zombie egg boomer`
> > I have _SilkSpawners_ and tried to use an egg from your plugin on a spawner, but it didn't work, it just spawns normal zombies, only if the apocalypse is active they will change to the plugin's zombies but randomly...
> > I believe giving a spawner won't be so "non-vanilla" like...
> 
> That is an interesting idea actually, will see if it is doable! Yeah it is fundamentally not possible to create truly new entities in a plugin, so for another plugin like SilkSpawner they will just look like normal zombie eggs.
> 
> Btw this is quite an interesting place to contact me, as the original issue is closed, but sure haha.

lol so do I create a new issue with this idea? 

I commented here because of the issue's topic, I was just about to ask the same, then when @archonxgames said something about a spawner mechanic, I came up with the idea of getting spawners from the plugin...

**Comment by EricLangezaal** [comment]
@joex92 Yeah you could do that if you want. I have seen it now of course so not strictly necessary, but if you have a suggestion in future that would be the correct place. 
Well what was asked originally is not possible at all (zombies in daylight), but spawners might be (you would still have to place them manually of course).
