### ISSUE TITLE
Zombies cannot swim

### ISSUE THREAD

**Issue by archonxgames** [EricLangezaal/ZombieApocalypse#5]
It seems that zombies from this plugin cannot traverse waterworks as well as normal mobs do, Im not sure if it's an effect of this plugin, but zombies cannot traverse deep pools of water and climb up one block high steps once fully submerged.

**Comment by EricLangezaal** [comment]
This is vanilla zombie behavior, it isn't specific to this plugin. I know this for certain, as my plugin doesn't change the behavior/movement of zombies, only their properties (health, speed etc), which do not influence which places a zombie can reach/try to walk to. Try using a default zombie for example, you will likely see that it too isn't able to traverse water well, having the same issues. (no 'land'-mobs in Minecraft can handle water particularly well).

**Comment by archonxgames** [comment]
Is it not possible to allow zombies to change into drowned without turning them back into normal zombies? Drowned are able to navigate in water much better than normal zombies can.

**Comment by EricLangezaal** [comment]
That is an interesting point actually. As I mentioned my custom zombies behave the same as normal zombies, so if they are under water long enough they should already become drowneds (but they will indeed lose their abilities). I can see if I can make them keep their ability whilst becoming a drowned, don't know yet.

**Comment by EricLangezaal** [comment]
Partially implemented in the newest version. When a zombie spawns/is spawned in water during an apocalypse, it is automatically converted to a drowned of that type (do keep in mind not all zombie properties work well for drowneds too). If a zombie converts, the converted drowned will also be an apocalypse drowned (albeit of a potentially other type).
