### ISSUE TITLE
Question (s)

### ISSUE THREAD

**Issue by Fireworkstars46** [EricLangezaal/ZombieApocalypse#9]
Can you add me on discord?

**Comment by EricLangezaal** [comment]
I do not use my private Discord for support. Support is handled exclusively through SpigotMC (and in exceptional cases, GitHub). If you want to send me personal message, please do so on SpigotMC. If you have a general question, ask it in the discussion thread of the plugin. GitHub is only relevant if you are a developer yourself or your question relates to the code directly.
